# Generated by Django 3.2.9 on 2021-11-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='slug',
        ),
    ]
