# Generated by Django 3.2.9 on 2021-11-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_remove_appointment_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime',
            new_name='appointment_datetime',
        ),
    ]
