# Generated by Django 3.2.9 on 2021-11-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_appointment_scheduler_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='scheduler_id',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
